# About
baseurl: "http://kokkos.org/"
title: "Kokkos"
languagecode: "en-us"
# Website menu
languages:
  en:
    menu:
      main:
      - name: "About"
        url: "/about/"
        weight: 10
      - identifier: "abstract"
        name: "Abstract"
        url: "/about/abstract/"
        parent: "About"
        weight: 1
      - identifier: "about-core"
        name: "Core"
        url: "/about/core/"
        parent: "About"
        weight: 2
      - identifier: "about-kernels"
        name: "Kernels"
        url: "/about/kernels/"
        parent: "About"
        weight: 3
      - identifier: "about-tools"
        name: "Tools"
        url: "/about/tools/"
        parent: "About"
        weight: 4
      - identifier: "about-tutorials"
        name: "Tutorials"
        url: "https://github.com/kokkos/kokkos-tutorials"
        parent: "About"
        weight: 5
      - identifier: "about-news"
        name: "News"
        url: "/blog/"
        parent: "About"
        weight: 6
      - name: "Repositories"
        url: "/repositories/"
        weight: 20
      - identifier: "repositories-core"
        name: "Core"
        url: "https://github.com/kokkos/kokkos"
        parent: "Repositories"
        weight: 1
      - identifier: "repositories-kernels"
        name: "Kernels"
        url: "https://github.com/kokkos/kokkos-kernels"
        parent: "Repositories"
        weight: 2
      - identifier: "repositories-tools"
        name: "Tools"
        url: "https://github.com/kokkos/kokkos-tools"
        parent: "Repositories"
        weight: 3
      - identifier: "repositories-tutorials"
        name: "Tutorials"
        url: "https://github.com/kokkos/kokkos-tutorials"
        parent: "Repositories"
        weight: 4
      - identifier: "documentation"
        name: "Documentation"
        url: "/documentation/"
        weight: 30
      - identifier: "blog"
        name: "Blog"
        url: "/blog/"
        weight: 40
      - name: "Outreach"
        url: "/outreach/"
        weight: 50
      - identifier: "outreach-events"
        name: "Events"
        url: "/outreach/events"
        parent: "Outreach"
        weight: 1
      - identifier: "outreach-publications"
        name: "Publications"
        url: "/outreach/publications"
        parent: "Outreach"
        weight: 2
      - identifier: "outreach-report-an-issue"
        name: "Report An Issue"
        url: "/outreach/report-an-issue"
        parent: "Outreach"
        weight: 3
      - identifier: "outreach-slack-channel"
        name: "Slack Channel"
        url: "https://app.slack.com/client/T5ASL2F1N"
        parent: "Outreach"
        weight: 4
      - name: "Community"
        url: "/community/"
        weight: 60
      - identifier: "team"
        name: "Team"
        url: "/community/team/"
        parent: "Community"
        weight: 1
      - identifier: "use-case-studies"
        name: "Use Case Studies"
        url: "/community/use-case-studies/"
        parent: "Community"
        weight: 2
      - identifier: "applications"
        name: "Applications"
        url: "/community/applications/"
        parent: "Community"
        weight: 3
      - identifier: "contact"
        name: "Contact"
        url: "/contact/"
        weight: 70
    weight: 7
# Path to take static files
staticDir:
  - assets
# Config search
params:
  search: true
outputs:
  home:
  - "HTML"
  - "JSON"
  - "RSS"
# Enable some html balise
markup:
  goldmark:
    renderer:
      unsafe: true