[docs]
    version = "0.9"
    basePath = "node_modules/@gethinode/hinode"

[navigation]
    anchor = true
    logo = "/img/kokkos-logo.png"
    color = "body"
    style = "light"
    fixed = true
    offset = "3.8em"
    search = true
    breadcrumb = false
    toc = true
    sidebar = true

[sections]
    [sections.blog]
        title = "Blog"
        sort = "date"
        reverse = true
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        separator = true
    [sections.projects]
        title = "Projects"
        sort = "title"
        reverse = false
        cols = 1
        color = "body-tertiary"
        padding = "3"
        header = "none"
        footer = "tags"
        orientation = "none"
        style = "border-1 card-emphasize"
        homepage = 3
        separator = false

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[style]
    primary = "#2596be"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    themeFont = "Inter"
    themeFontPath = "/fonts"

[schema]
    type = "Organization"
    name = "Hinode"
    locale = "en-US"
    github = "https://github.com/gethinode/hinode"
    section = "blog"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[links]
    bs_badge_heading = "https://getbootstrap.com/docs/5.2/components/badge/#headings"
    hinode_docs = "https://gethinode.com/docs"
    hugo_imaging = "https://gohugo.io/content-management/image-processing/#imaging-configuration"
    mozilla_image = "https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images"
    observatory = "https://observatory.mozilla.org/analyze/demo.gethinode.com"
    pagespeed = "https://pagespeed.web.dev/report?url=https%3A%2F%2Fdemo.gethinode.com%2F"
    utterances = "https://utteranc.es"
 